### PR TITLE
Fixed issue 31/32 by passing combinedSettings into numericField_Blur

### PR DESCRIPTION
**Pull request by leesaxby**
Appear to have fixed issues 31/32 by passing combinedSettings into numericField_Blur instead of settings.

### CODE REVIEW

**Comment by KevinSheedy** [comment]
Thanks @leesaxby 
In the diff, it looks like the file encoding might have been changed so I went ahead and recommitted the fix.
(let me know if you want to get your name on the contributors list and we can figure it out. Maybe repush the fix without the encoding change and I'll try merge it)

**Comment by KevinSheedy** [comment]
Oh and looks like the encoding problem was on my side, I accidentally encoded the file in a windows encoding

**Comment by leesaxby** [comment]
@KevinSheedy No problem.
Yes, you can add me to the contributors list.

Thanks

**Comment by KevinSheedy** [comment]
@leesaxby I can't see a way to manually add you as a contributor. I think you might need to raise a new PR with a dummy commit (add a comment or something) and I can merge it in

**Pull request closed without merging**
